//! Embedded SPA assets (table generated by `build.rs` — docs/UI.md § 3).

include!(concat!(env!("OUT_DIR"), "/assets_generated.rs"));

/// Resolves a request path to `(content type, bytes)`.
///
/// `/` serves `index.html`. Lookup is exact against the embedded table,
/// so path traversal cannot escape it by construction.
pub fn lookup(path: &str) -> Option<(&'static str, &'static [u8])> {
    let relative = match path.trim_start_matches('/') {
        "" => "index.html",
        trimmed => trimmed,
    };
    ASSETS
        .iter()
        .find(|(name, _)| *name == relative)
        .map(|(name, bytes)| (content_type(name), *bytes))
}

/// Maps an asset filename to its `Content-Type` header value.
fn content_type(name: &str) -> &'static str {
    match name.rsplit('.').next() {
        Some("html") => "text/html; charset=utf-8",
        Some("css") => "text/css; charset=utf-8",
        Some("js") => "text/javascript; charset=utf-8",
        Some("svg") => "image/svg+xml",
        Some("json") => "application/json",
        Some("png") => "image/png",
        _ => "application/octet-stream",
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn root_serves_index_html() {
        let (content_type, bytes) = lookup("/").expect("index.html is embedded");
        assert_eq!(content_type, "text/html; charset=utf-8");
        assert!(!bytes.is_empty());
    }

    #[test]
    fn explicit_index_path_matches_root() {
        assert_eq!(lookup("/index.html"), lookup("/"));
    }

    #[test]
    fn unknown_and_traversal_paths_are_rejected() {
        assert_eq!(lookup("/missing.js"), None);
        assert_eq!(lookup("/../Cargo.toml"), None);
        assert_eq!(lookup("/../../etc/passwd"), None);
    }
}
